### ISSUE TITLE
webstrom vue debug

### ISSUE THREAD

**Issue by 836056404** [prigara/debugging-webpack#4]
![image](https://user-images.githubusercontent.com/30099739/53691044-36d5d580-3db1-11e9-9499-4a3f8a04ad39.png)
2018.3.5  why this is  undefined？

**Comment by prigara** [comment]
Hello, as I've mentioned in this [comment](https://github.com/JetBrains/webstorm-samples/issues/2#issuecomment-469593285), please contact the IDE tech support and provide a sample app.
